name: Multi-Job Workflows

on: [push,pull_request]

jobs: 
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Print Hello World
              run: echo "Hello World"

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello
              run: echo "Hello job-2"

    job3:
        runs-on: ubuntu-latest
        steps:
            - name: Print helloooooo
              run: echo "helooooooooooo"
