name: Multi-Job Workflows

on: [push,pull_request]

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Print Hello World
              run: echo "Hello World"

    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Print Hello
              run: echo "Hello job-2"

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Print helloooooo
              run: echo "helooooooooooo"
